databases:
  - name: pawhaven-db
    databaseName: petcare_db
    user: petcare_user

services:
  - type: web
    name: pawhaven-backend
    runtime: docker
    dockerfilePath: ./petcare/Dockerfile
    dockerContext: ./petcare
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: pawhaven-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        value: petcare.customerservices@gmail.com
      - key: MAIL_PASSWORD
        value: gkufzulypvmhzulh
      - key: PAYPAL_CLIENT_ID
        value: your_paypal_client_id
      - key: PAYPAL_CLIENT_SECRET
        value: your_paypal_client_secret
    healthCheckPath: /api/health
